language: objective-c
osx_image: xcode10
xcode_project: testRepo2.xcodeproj
xcode_scheme: testRepo2
xcode_sdk: iphonesimulator12.1
env:
  global:
  - |
    - APP_NAME="testRepo2"
    - 'DEVELOPER_NAME="GTME_ProvProf_Dev"'
    - PROFILE_NAME="development-provisioning-profile"
  - secure: LkVxPdasrGGP5T3Q/OLnhyGtcHS4JvmcDuyel/sECBUrum4iTsTw+CKC1KAFWqk+AkfWlv0AYwQ/Ks8ZxIrtzK5BhiHbq93qJqCzp162FzkMp4xMgyWVZQB42DVSHxDmOzLl0OOsn4DFMv6puKMjX2hEMgylIiULhXNgOkIWelTJNZWgYlncZqGUgirknVy4ANWA37v8VfUiQReBG5YyuN8xauZ6U0W6C6Eg4q2c/+Rd/nBlWz+27BMCr3AWhjWM/NEuAet4/DF+haM1eQKJTfSlb2gpkSfozbAC3FrVS7CpidgPvLGXI0jZcg+1D7hO7RDqCiUfzOn2aD59dqRxSQNayleql8iQ/Rq6pxdYvOKodaJ3nqFYKveLE8bU1dg1ZJPGDjwKH1TDtJ3ydFcqYK+WmJU0WndATEspU897DbJjkPxmTew0K+ft5EX6O8sH8IUc9LlznUlr8TQMvzTwIzwmSgfrvjbnS3XMqJBLBtw31qmKOD34Bq+/L5YGqrsaFLtQsscBONYyIibXvpC2/CP9Q+5i1rHQm1Z7pEYUuMhBQYRDp9/BtcbhcIjhjYJbVWPZ3i+WH5S8IEhRfqjthW34WXJ0a7pZf93Z4FEgHLE7xrjbVpF+9+zOvMDzEM65ADYI1OVLEdgXO7ngql2p8+onOI8pNzNqiGaQ++ZDhmM=
deploy:
  provider: releases
  api_key:
    secure: LzIR7iXysify/UZ9DrNWDyrudivLKubnQeBSETfPXE4eUoOSa3xQZO1BXXAtoWThxDQG3yWReKTuuXaCjNW0mzObRMYR7mDm80FTvg6p80K4iUa5ruKjgDBPLf6hjvcKVSeyK0qJ3L3Ihkq0X6fJ6qAOxnwZuB5bpPGmSh9SaHjiZk1wWYAMlQWK4dyWGxt9zStP78iDnwVcKFY5qATVmrYWV0eiDC1O6BE8CULR1EHAGducwIv1pwsGC+H6FMJ1hvpYi2EUyPj9xRnjdUms1VdlRolbtHFFYiJjroVh8d6hRW8GDIB+2M2ZQegNe22+TxU6SXMJ9Eh2C2/tOrJHysAAtBIR6mJjEporjm8zNDYqCJSwCmiNjQN8qkRUoQqn2J5o17QHQtKjlgpereLTX+henmX6LrIGWlGwvP/NQqnPKVYlWLd7a5weeWDjuaGSf7qRMX8xHjoOnXpg9bsJwBJiCPF7G7lVglkLBjVu9EhSbT8wy01k/ASDgSzzpjXUzEiGNgEpA0l7hhOryDo+9b1jD+yQ5VMGDbviDGln+dywk0khArf3ThkoFwiJg5H+oJPmyTJWnJ66jN9dor8+81R25gaotkQxadAViqLIjFL/W38ylIMUM2THDtkxZ3f63h2ACR0r72/pb6N/k5wsuSdD0q7nX4tRYFv7zGRQA0k=
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: surekhas-tml/testRepo2
    branch: develop
    skip_cleanup: true
before_deploy:
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
- export RELEASE_PKG_FILE=$(ls *.ipa)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
before_script:
- "./scripts/add-key.sh"
script:
- "./scripts/build.sh"
